[package]
name = "rust-cli-pomodoro"
version = "1.0.0"
authors = ["24seconds <24crazyoung@gmail.com>"]
edition = "2021"
rust-version = "1.59"
description = """
rust-cli-pomodoro manages your time!
"""
homepage = "https://github.com/24seconds/rust-cli-pomodoro"
repository = "https://github.com/24seconds/rust-cli-pomodoro"
readme = "README.md"
keywords = ["pomodoro", "notification", "terminal-app"]
categories = ["command-line-utilities"]
license = "Beerware"
exclude = ["/assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
clap = "2.33.3"
chrono = "0.4.19"
chrono-tz=  "0.6.0"
gluesql = { version = "0.10.2", features = ["memory-storage"] }
notify-rust = "4.5.4"
log = "0.4.0"
env_logger = "0.9.0"
tabled = "0.5.0"
serde_json = "1.0.59"
serde = "1.0.130"
reqwest = { version = "0.11", features = ["json"] }

[[bin]]
name = "pomodoro"
path = "src/main.rs"
