[package]
name = "rust-cli-pomodoro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
clap = "2.33.3"
chrono = "0.4.19"
chrono-tz=  "0.6.0"
gluesql = { git = "https://github.com/24seconds/gluesql" }
notify-rust = "4.5.4"
