name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  
  rust_fmt:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions/checkout@v3
      - name: Add rust format
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          default: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo fmt -- --check

  run_test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo test --verbose
